### ISSUE TITLE
[MLSS] Super Hammers not Updating to Ultra Hammers

### ISSUE THREAD

**Issue by therawkhawk64** [jamesbrq/ArchipelagoMLSS#1]
So, I was playing in an asynch with several friends, and I ended up finding my Ultra Hammers at Oho Oasis Thunderhand check. However, when I obtained the check, my hammers never updated to Ultra Hammers. PopTracker recognized that I had Ultras and updated my checks, but my hammers never updated. I restarted both the game and the client.

**Comment by jamesbrq** [comment]
This is fixed and slated to be in AP 0.5.1
